/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prueba_mov;

import Clases.Producto;
import Vista.Ingreso;
import java.util.ArrayList;

/**
 *
 * @author USUARIO
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    Ingreso ing;
    RegistroProd rp;
    RegistroUsuario ru;
    ModificarUsuario mu;
    ModificarProducto mp;
    ActualizarProducto ap;
    ActualizarUsuario au;
    static ArrayList<Producto> productos =new ArrayList<Producto>();
    public Inicio() {
        initComponents();
        ing =new Ingreso();
        rp=new RegistroProd();
    ru=new RegistroUsuario();
    mu=new ModificarUsuario();
    mp=new ModificarProducto ();
    ap=new ActualizarProducto ();
    au= new ActualizarUsuario(); 
    lbTipoUsuario.setText(ing.tipo);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbUsuario = new javax.swing.JLabel();
        lbTipoUsuario = new javax.swing.JLabel();
        btnnuevoP = new javax.swing.JButton();
        btnNuevoU = new javax.swing.JButton();
        btnModiP = new javax.swing.JButton();
        btnModifU = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mRegistro = new javax.swing.JMenu();
        mCambios = new javax.swing.JMenu();
        mReporte = new javax.swing.JMenu();
        mSalir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio");

        lbUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/20x20-USUARIO.png"))); // NOI18N
        lbUsuario.setText("Usuario");

        btnnuevoP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/producto.png"))); // NOI18N
        btnnuevoP.setText("Nuevo Producto");
        btnnuevoP.setEnabled(false);
        btnnuevoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuevoPActionPerformed(evt);
            }
        });

        btnNuevoU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/addUser20.png"))); // NOI18N
        btnNuevoU.setText("Nuevo Usuario");
        btnNuevoU.setEnabled(false);
        btnNuevoU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoUActionPerformed(evt);
            }
        });

        btnModiP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/30x30-UPDATE.png"))); // NOI18N
        btnModiP.setText("Producto");
        btnModiP.setEnabled(false);
        btnModiP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModiPActionPerformed(evt);
            }
        });

        btnModifU.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/30x30-UPDATE.png"))); // NOI18N
        btnModifU.setText("Usuarios");
        btnModifU.setEnabled(false);
        btnModifU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifUActionPerformed(evt);
            }
        });

        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/40x40-EMPRESAREPORTE.png"))); // NOI18N
        btnReport.setText("Reporte producto");
        btnReport.setEnabled(false);
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/70x70-EMPRESABAJA.png"))); // NOI18N
        btnSalir.setText("Salir Sistema");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        mRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/40x40-REMISIONES_1.png"))); // NOI18N
        mRegistro.setText("Registro");
        mRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mRegistroMouseClicked(evt);
            }
        });
        jMenuBar1.add(mRegistro);

        mCambios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/70x70-EMPRESAMODIFICAR.png"))); // NOI18N
        mCambios.setText("Cambios");
        mCambios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mCambiosMouseClicked(evt);
            }
        });
        jMenuBar1.add(mCambios);

        mReporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/30x30-REPORTE.png"))); // NOI18N
        mReporte.setText("Reportes");
        mReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mReporteMouseClicked(evt);
            }
        });
        jMenuBar1.add(mReporte);

        mSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/20x20-SALIR.png"))); // NOI18N
        mSalir.setText("Salir");
        jMenuBar1.add(mSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(205, Short.MAX_VALUE)
                .addComponent(lbUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbTipoUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModifU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModiP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNuevoU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnnuevoP, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                    .addComponent(lbTipoUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(btnnuevoP, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNuevoU, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModiP)
                .addGap(8, 8, 8)
                .addComponent(btnModifU, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnReport, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnnuevoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuevoPActionPerformed
        // TODO add your handling code here
        rp.setVisible(true);
    }//GEN-LAST:event_btnnuevoPActionPerformed

    private void btnModiPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModiPActionPerformed
        // TODO add your handling code here:
        mp.setVisible(true);
    }//GEN-LAST:event_btnModiPActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnReportActionPerformed

    private void mRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mRegistroMouseClicked
        // TODO add your handling code here:
        this.btnModiP.setEnabled(false);
        this.btnModifU.setEnabled(false);
        this.btnNuevoU.setEnabled(true);
        this.btnReport.setEnabled(false);
        this.btnnuevoP.setEnabled(true);
        
        
    }//GEN-LAST:event_mRegistroMouseClicked

    private void mCambiosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mCambiosMouseClicked
        // TODO add your handling code here:
        this.btnModiP.setEnabled(true);
        this.btnModifU.setEnabled(true);
        this.btnNuevoU.setEnabled(false);
        this.btnReport.setEnabled(false);
        this.btnnuevoP.setEnabled(false);
    }//GEN-LAST:event_mCambiosMouseClicked

    private void mReporteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mReporteMouseClicked
        // TODO add your handling code here:
        this.btnModiP.setEnabled(false);
        this.btnModifU.setEnabled(false);
        this.btnNuevoU.setEnabled(false);
        this.btnReport.setEnabled(true);
        this.btnnuevoP.setEnabled(false);
    }//GEN-LAST:event_mReporteMouseClicked

    private void btnNuevoUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUActionPerformed
        // TODO add your handling code here:
        ru.setVisible(true);
    }//GEN-LAST:event_btnNuevoUActionPerformed

    private void btnModifUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifUActionPerformed
        // TODO add your handling code here:
        mu.setVisible(true);
    }//GEN-LAST:event_btnModifUActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        ing.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnModiP;
    private javax.swing.JButton btnModifU;
    private javax.swing.JButton btnNuevoU;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnnuevoP;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lbTipoUsuario;
    private javax.swing.JLabel lbUsuario;
    private javax.swing.JMenu mCambios;
    private javax.swing.JMenu mRegistro;
    private javax.swing.JMenu mReporte;
    private javax.swing.JMenu mSalir;
    // End of variables declaration//GEN-END:variables
}
